### ISSUE TITLE
Fork of parity-bridge?

### ISSUE THREAD

**Issue by pkieltyka** [poanetwork/poa-bridge#111]
Hello,

I was just wondering whats the difference between this repo/project and https://github.com/paritytech/parity-bridge

thanks. nice work btw!

**Comment by akolotov** [comment]
There is a bunch of changes in Rust side, e.g. gas price oracle support, usage RPC instead of IPC, transaction sending performance enhancement, contract deployment is done as part of separate project. Solidity part is completely re-worked: brige contracts are upgradable, the token code was separated from the bridge contracts, set of validators could be changed on the fly.

**Comment by pkieltyka** [comment]
Nice. Those would be very useful things in a list for new users looking at
both parity-bridge and POA to know the differences.

**Comment by igorbarinov** [comment]
@akolotov could you please update README and add the diff?

**Comment by igorbarinov** [comment]
@akolotov up
