### ISSUE TITLE
gasPrice for Foreign chain transactions should be requested through gasprice.poa.network

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/poa-bridge#16]
As an example, ICO wizard makes an API call to https://gasprice.poa.network/, get the fastest or lowest(@igorbarinov )
IF service is not available, use hardcoded value.
I'd recommend using `standard` value from https://gasprice.poa.network/

Should be done on Rust side

https://gasprice.poa.network/

@akolotov please approve

**Comment by akolotov** [comment]
:) it was in my todo of issues to create for the projects.

Since personally I don't like the idea of yet another service to be requested, I thought about an oracle which will put gas price into the bridge contract. My rationales are: 
* we need two different prices: one for POA and another for Foundation;
* we are tying with POA in the core of the bridge without strict necessity.

My suggestion are
1. create public fields `gasPrice` in both contracts `HomeBridge` and `ForeignBridge`;
2. initialize `gasPrice` as part of deployment of contracts.

This will be _Phase I_

Later in _Phase II_ we will:
1. provide `updateGasPrice` method in both contracts to set new `gasPrice` with some consensus;
2. develop a tool or the bridge subsystem which will call `updateGasPrice` periodically.

@rstormsf if you agree let's change the label to _solidity_ and modify the title to reflect the idea of the changing.

**Comment by akolotov** [comment]
@rstormsf @igorbarinov did you discuss it? should we have a call together to discuss it?

**Comment by igorbarinov** [comment]
We have `gasprice.poa.network` on support and monitoring. It's as good as a supported onchain oracle.  I'd like to stick with it with an option to hardcode gasprice if that host is not available. I suggest having 21Gwei as a hardcoded parameter.

**Comment by igorbarinov** [comment]
@phahulin could you create a public dashboard in site24x7 for gasprice oracle 
for host health and API health

@banteg thank you for the code https://github.com/banteg/gasprice

**Comment by phahulin** [comment]
@igorbarinov please check out this dashboard https://www.site24x7.com/public/dashboard/8s1wsTAc/g8Ipq0FBcZ91xw291jfLWVBkJ0jC5DLujR/xAyNIDrraYAkxnvoKUBHlauhy7dDGbQxteFTkHMOoiMhfYD63Eyzl6uNzRhBp6KHZIsTkfWPbhiydvLmPEfG

**Comment by igorbarinov** [comment]
Nice, could we have outage number? duration?
disk space also will be good to know

**Comment by igorbarinov** [comment]
Pashi, nice dashboard! But gasprice oracle is out of sync 🙈😬

- please add logging for gasprice and parity service
- add corresponding checks on log files

**Comment by akolotov** [comment]
OK. Here is my suggestion:
1. we introduce public fields `gasPrice` in both contracts `HomeBridge` and `ForeignBridge`;
2. gasPrice will be initialized as part of deployment of contracts:
    * it equals 1 gwei in `HomeBridge`
    * it equals 21 gwei in  `ForeignBridge`
3. In order to perform `deposit_relay` or `withdraw_confirm` the bridge will request http://gasprice.poa.network and if it is not available `gasPrice` of `ForeignBridge` will be requested.
4. In order to perform `withdraw_relay`, `gasPrice` of `HomeBridge` will be requested.

**Comment by rstormsf** [comment]
Bridge should read from config.toml
```
gas_price_oracle_url = "https://gasprice.poa.network/"
gas_price_speed_type = "fast"
```
and receive this value in gwei, convert to hex value in wei for signing tx on foreign.
this value could be cached only for short period of time ( 5-10min)

**Comment by akolotov** [comment]
Here is the recent requirements based on discussions:
1. We do provide options in `[home]` and `[foreign]` of configuration file to allow configure a JSON source of gas price:
```
gas_price_oracle_url = "https://gasprice.poa.network/"
gas_price_speed_type = "fast"
gas_price_update_timeout = 600
```
2. We expect that the gas price oracle will return information in the following form:
`{"block_number":5559089,"block_time":14.824,"instant":50.0,"standard":4.0,"slow":2.0,"fast":5.0,"health":true}`
3. We add the parameter `default_gas_price` in [home]` and `[foreign]` 
4. We remove `gas_price` from `[transactions]` for `deposit_relay`, `withdraw_confirm` and `withdraw_relay`.

The logic is as follows:
1. Try to get gas price from the oracle for the corresponding network. It needs to be done on regular basis with usage of `gas_price_update_timeout`.
2. If the oracle is not accessible or returns incorrect information, the default gas price (`default_gas_price`) is used for the corresponding network.

**Comment by DrPeterVanNostrand** [comment]
In the JSON returned from `GET https://gasprice.poa.network`:

```json
{
  "block_number": 5584026,
  "block_time": 14.307,
  "instant": 41,
  "standard": 5,
  "slow": 4,
  "fast": 6,
  "health": true
}
```

does anyone know what does the "health" key-value pair means? Does "health: true" indicate that the gas prices values returned from the API are trustworthy, while `health: false` indicates otherwise?  If that is the case, then we should use the default gas price in the cases of:

1. `health: false`
2. request duration to `gas_price_oracle_url` has exceeded `gas_price_update_timeout`?

**Comment by banteg** [comment]
`health: false` means the node is not fully synced and the numbers are off.

**Comment by DrPeterVanNostrand** [comment]
Ok, cool. Thanks!
